#!/bin/bash -x
#SBATCH --account=mul-tra
#SBATCH --job-name=ONE_SOLVE
#SBATCH --nodes=81
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=00:05:00
#SBATCH --partition=batch



export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
module load GCC/11.3.0
module load OpenMPI/4.1.4


date
make clean
make -j 64


date
. run -i "sample.ini"

date


